# -*- coding: utf-8 -*-
"""ip adresi ile konum bulma

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AYBxguF892zBvqsvEBo8ry7on-ek0Muj
"""

import requests

def ip_konum_getir(ip_address):
    try:
        cevap = requests.get(f"http://ipinfo.io/{ip_address}/json")
        veri = cevap.json()

        if "loc" not in veri:
            return f"IP Adresi: {ip_address}, Konum bilgisi bulunamadı."
        else:
            location = veri["loc"]
            return f"IP Adresi: {ip_address}, Konum: {location}"

    except Exception as e:
        return f"Hata: {e}"


if __name__ == "__main__":
    kullanici_ip = input("Lütfen bir IP adresi girin: ")
    cikti = ip_konum_getir(kullanici_ip)
    print(cikti)